# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================JacksonConfiguration
logging:
  level:
    ROOT: INFO
    com.github.vazmin: DEBUG

server:
  port: 8100

mybatis:
  configuration:
    map-underscore-to-camel-case: true

spring:
  jta:
    enabled: true
    service: com.atomikos.icatch.standalone.UserTransactionServiceFactory
    max-actives: 200
    enable-logging: false
    atomikos:
      datasource:
        mp:
          unique-resource-name: dataSourceManagePlatform
          max-pool-size: 5
          min-pool-size: 1
          max-life-time: 20000
          borrow-connection-timeout: 10000
          xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
          xa-properties:
            user: root
            password: "chwing"
            URL: jdbc:mysql://localhost:3306/manage_platform?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
  jackson:
    default-property-inclusion: non_null
    deserialization: {
      fail_on_unknown_properties: false
    }


manage:
  client-app:
    name: "manage-simple"
  security:
    authentication:
      admin:
        username: admin
        password: $2a$10$UCXTYtesFBmpLKo5UJAiUOVJFwY/HE/tbe0lFQOoCFmMzruKk9ccy
      jwt:
        base64-secret: g3xpUK5dCaKBXCYqI2CHDS881Zr0+HzqWMDqSaIaAzp3/GphDPElXRQAv1wpEqdqiiT5ZqGHYM9Hgirt4nwTDg==