# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================JacksonConfiguration

server:
  port: 8100

mybatis:
  configuration:
    map-underscore-to-camel-case: true

spring:
  jta:
    enabled: true
    service: com.atomikos.icatch.standalone.UserTransactionServiceFactory
    max-actives: 200
    enable-logging: false
    atomikos:
      datasource:
        mp:
          unique-resource-name: dataSourceManagePlatform
          max-pool-size: 5
          min-pool-size: 1
          max-life-time: 20000
          borrow-connection-timeout: 10000
          xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
          xa-properties:
            user: root
            password: "0302"
            URL: jdbc:mysql://localhost:3306/manage_platform?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
# application:
#  tx-map: {
#            "insert*": "PROPAGATION_REQUIRED,-Throwable",
#            "update*": "PROPAGATION_REQUIRED,-Throwable",
#            ""
#            // 新增
#            transactionAttributes.setProperty("insert*",
#            "PROPAGATION_REQUIRED,-Throwable");
#            transactionAttributes.setProperty("update*",
#            "PROPAGATION_REQUIRED,-Throwable");
#            transactionAttributes.setProperty("delete*",
#            "PROPAGATION_REQUIRED,-Throwable");
#            transactionAttributes.setProperty("select*",
#            "PROPAGATION_REQUIRED,-Throwable,readOnly");
#  }